"""Headless workflow facades used by canonical notebooks."""

from .cycle import (
    CycleCondition,
    CycleExperimentSpec,
    CycleWorkflowSpec,
    prepare_cycle_experiment,
    run_cycle_workflow,
)
from .eis import (
    EisExperimentSpec,
    EisWorkflowSpec,
    LifecycleEisSpec,
    prepare_eis_experiment,
    run_eis_workflow,
    run_quick_eis_sections,
    summarize_quick_components,
)
from .frequency import (
    FrequencyWorkflowSpec,
    build_frequency_waveform_preview,
    prepare_frequency_workflow,
    run_frequency_workflow,
)
from .lifecycle_heat import (
    ContactResistanceCase,
    EntropyCalibrationSpec,
    LifecycleHeatCondition,
    LifecycleHeatWorkflowSpec,
    run_lifecycle_heat_workflow,
)
from .psd import (
    ComsolDvSpec,
    ComsolRawSpec,
    PsdDatasetSpec,
    PsdWorkflowSpec,
    build_comsol_histogram_frame,
    comsol_histogram_to_java,
    fit_dv_to_comsol_histogram,
    load_psd_materials_from_registry,
    raw_psd_to_comsol_histogram,
    run_psd_workflow,
)
from .pulse import (
    PulseWorkflowSpec,
    build_adjusted_capacity_table,
    prepare_pulse_workflow,
    run_pulse_workflow,
)
from .regional_coupled_aging import (
    LifecycleSpec,
    ReducedNetworkCase,
    ReducedNetworkSpec,
    RegionalCoupledAgingWorkflowSpec,
    RegionalDFNCase,
    TransientDFNSpec,
    build_region_configs,
    run_regional_coupled_aging_workflow,
)

__all__ = [
    "ContactResistanceCase",
    "ComsolDvSpec",
    "ComsolRawSpec",
    "CycleCondition",
    "CycleExperimentSpec",
    "CycleWorkflowSpec",
    "EisExperimentSpec",
    "EisWorkflowSpec",
    "EntropyCalibrationSpec",
    "FrequencyWorkflowSpec",
    "LifecycleEisSpec",
    "LifecycleHeatCondition",
    "LifecycleHeatWorkflowSpec",
    "LifecycleSpec",
    "PsdDatasetSpec",
    "PsdWorkflowSpec",
    "PulseWorkflowSpec",
    "ReducedNetworkCase",
    "ReducedNetworkSpec",
    "RegionalCoupledAgingWorkflowSpec",
    "RegionalDFNCase",
    "TransientDFNSpec",
    "build_adjusted_capacity_table",
    "build_comsol_histogram_frame",
    "build_frequency_waveform_preview",
    "build_region_configs",
    "comsol_histogram_to_java",
    "fit_dv_to_comsol_histogram",
    "load_psd_materials_from_registry",
    "prepare_cycle_experiment",
    "prepare_eis_experiment",
    "prepare_frequency_workflow",
    "prepare_pulse_workflow",
    "raw_psd_to_comsol_histogram",
    "run_cycle_workflow",
    "run_eis_workflow",
    "run_frequency_workflow",
    "run_lifecycle_heat_workflow",
    "run_psd_workflow",
    "run_pulse_workflow",
    "run_quick_eis_sections",
    "run_regional_coupled_aging_workflow",
    "summarize_quick_components",
]
